#page title
page_title                                : Yabs                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://www.youtube.com/watch?v=dQw4w9WgXcQ                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Yabs                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 0.00                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Jobs. Done. Task Sharing.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Kyle Tran                                
your_link                                 : kyletran77@gmail.com                      
your_city                                 : Irvine                                
email_address                             : Kyle Tran
facebook_username                         :                                           
instagram_username                        : ebaehr
twitter_username                          : ebaehr
github_username                           : emilbaehr
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Task-sharing
    description                           : Stop delaying your tasks that you don't want to do - let others do it for you. With Yab.
    fontawesome_icon_name                 : magic
    
  - title                                 : #iPhone Device Preview
    description                           : #Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : #mobile

  - title                                 : #Video Support
    description                           : #Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : #play-circle

  - title                                 : Need to get laundaries done?
    description                           : Don't dread hours on the laundry machine when you are busy! Ask a fellow student with Yab.
    fontawesome_icon_name                 : bell-slash

  - title                                 : Easy Search
    description                           : No more awkward calls and messages for a small favor. Get stuffs done in five minutes with few clicks.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Security
    description                           : Only authorized university students are eligible to use - no strangers.
    fontawesome_icon_name                 : star

  - title                                 : Smart App Banner
    description                           : Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : # Social Links
    description                           : # Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # link

  - title                                 : #FontAwesome Support
    description                           : #Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000080"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
